export type Question = {
  id: number;
  grade: number;
  difficulty: number;
  topic: string;
  question: string;
  options: string[];
  correct: number;
  explanation?: string; // қысқа түсіндірме
  given?: string[]; // Берілген: KaTeX block mode
  solutionSteps?: string[]; // Шешуі: KaTeX block mode
  finalAnswer?: string; // Жауабы: KaTeX block mode
};

export const questions: Question[] = [
  {
    id: 1,
    grade: 5,
    difficulty: 1,
    topic: "Натурал сандар",
    question: "Егер x + 7 = 15 болса, x неге тең?",
    options: ["6", "7", "8", "9"],
    correct: 2,
  },
  {
    id: 2,
    grade: 5,
    difficulty: 1,
    topic: "Көбейту",
    question: "12 · 12 нәтижесі қандай?",
    options: ["124", "134", "144", "154"],
    correct: 2,
  },
  {
    id: 3,
    grade: 5,
    difficulty: 2,
    topic: "Жай сандар",
    question: "Төмендегілердің қайсысы жай сан?",
    options: ["9", "15", "17", "21"],
    correct: 2,
  },
  {
    id: 4,
    grade: 5,
    difficulty: 1,
    topic: "Бөлу",
    question: "48-ді 6-ға бөлгендегі бөлінді неге тең?",
    options: ["6", "7", "8", "9"],
    correct: 2,
  },
  {
    id: 5,
    grade: 5,
    difficulty: 2,
    topic: "Теңдеу",
    question: "3 · y = 24 болса, y неге тең?",
    options: ["6", "7", "8", "9"],
    correct: 2,
  },
  {
    id: 6,
    grade: 5,
    difficulty: 1,
    topic: "Қосу",
    question: "256 + 144 қосындысы неге тең?",
    options: ["390", "400", "410", "420"],
    correct: 1,
  },
  {
    id: 7,
    grade: 5,
    difficulty: 2,
    topic: "Бөлу қалдығы",
    question: "37-ні 5-ке бөлгендегі қалдық қандай?",
    options: ["0", "1", "2", "3"],
    correct: 2,
  },
  // Grade 5, difficulty 3 — multi-step, mixed operations, word problems
  {
    id: 8,
    grade: 5,
    difficulty: 3,
    topic: "Сөздік есеп",
    question: "Айдана 120 теңгелік 4 дәптер сатып алды. Ол кассаға 500 теңге берді. Қайтарылатын ақша қанша теңге?",
    options: ["15", "20", "25", "30"],
    correct: 1,
  },
  {
    id: 9,
    grade: 5,
    difficulty: 3,
    topic: "Бөліктер",
    question: "Қорапта 36 алма бар. Оның 1/3-ін бір топ алды, қалғанының жартысын екінші топ алды. Екінші топ неше алма алды?",
    options: ["10", "12", "14", "18"],
    correct: 1,
  },
  {
    id: 10,
    grade: 5,
    difficulty: 3,
    topic: "Қозғалыс есебі",
    question: "Поезд алдымен 3 сағатта 240 км жүрді. Келесі 2 сағатта ол сағатына 10 км аз жылдамдықпен жүрді. Поезд барлығы неше км жол жүрді?",
    options: ["360", "380", "400", "420"],
    correct: 1,
  },
  {
    id: 11,
    grade: 5,
    difficulty: 3,
    topic: "Периметр және аудан",
    question: "Тік төртбұрыштың ұзындығы 15 см, ені 8 см. Оның периметрі мен ауданының қосындысы неге тең?",
    options: ["156", "166", "176", "186"],
    correct: 1,
  },
  {
    id: 12,
    grade: 5,
    difficulty: 3,
    topic: "Бөліктер (сөздік)",
    question: "Дүкенде 48 кг қант болды. Бірінші күні оның 1/4-і, екінші күні қалғанының 1/3-і сатылды. Барлығы неше кг қант сатылды?",
    options: ["20", "22", "24", "28"],
    correct: 2,
  },
  {
    id: 13,
    grade: 5,
    difficulty: 3,
    topic: "Теңдеу (екі белгісіз)",
    question: "Екі санның қосындысы 90, айырмасы 20. Кіші сан қандай?",
    options: ["30", "35", "40", "45"],
    correct: 1,
  },
  {
    id: 14,
    grade: 5,
    difficulty: 3,
    topic: "Қозғалыс (келу-кету)",
    question: "Автобуста бастапқыда 25 адам болды. Ол 4 рет тоқтады: әр тоқтағанда 12 адам түсіп, 7 адам отырды. Соңғы тоқтағаннан кейін автобуста неше адам қалды?",
    options: ["3", "5", "7", "9"],
    correct: 1,
  },
  {
    id: 15,
    grade: 5,
    difficulty: 3,
    topic: "Баға есебі",
    question: "3 дәптер мен 2 қалам 190 теңге тұрады. Бір дәптер 30 теңге болса, бір қалам неше теңге?",
    options: ["45", "50", "55", "60"],
    correct: 1,
  },
  {
    id: 16,
    grade: 5,
    difficulty: 3,
    topic: "Теңдеу (көбейту мен қосу)",
    question: "Бір санның 5 еселенгені мен 12-нің қосындысы 57-ге тең. Осы сан қандай?",
    options: ["7", "8", "9", "10"],
    correct: 2,
  },
  {
    id: 17,
    grade: 5,
    difficulty: 3,
    topic: "Қатынас (сөздік)",
    question: "Бақшада барлығы 84 гүл бар — раушандар мен қалампырлар. Раушандар саны қалампырлардан 2 есе көп. Қалампыр нешеу?",
    options: ["24", "28", "32", "36"],
    correct: 1,
  },
  // ——— 40 new grade-5 questions (id 18–57) ———
  // Easy (difficulty 1–2)
  {
    id: 18,
    grade: 5,
    difficulty: 1,
    topic: "Сандар және амалдар",
    question: "125 + 275 қосындысы неге тең?",
    options: ["390", "400", "410", "420"],
    correct: 1,
  },
  {
    id: 19,
    grade: 5,
    difficulty: 1,
    topic: "Сандар және амалдар",
    question: "17 · 4 нәтижесі қандай?",
    options: ["64", "68", "72", "76"],
    correct: 1,
  },
  {
    id: 20,
    grade: 5,
    difficulty: 1,
    topic: "Геометрия",
    question: "Шаршының қабырғасы 9 см болса, периметрі неше см?",
    options: ["32", "36", "40", "45"],
    correct: 1,
  },
  {
    id: 21,
    grade: 5,
    difficulty: 1,
    topic: "Бөлшектер",
    question: "1/2 + 1/4 қосындысы неге тең?",
    options: ["1/3", "2/6", "3/4", "2/4"],
    correct: 2,
  },
  {
    id: 22,
    grade: 5,
    difficulty: 1,
    topic: "Сандар және амалдар",
    question: "96-ны 8-ге бөлгендегі бөлінді неге тең?",
    options: ["10", "11", "12", "13"],
    correct: 2,
  },
  {
    id: 23,
    grade: 5,
    difficulty: 2,
    topic: "Сандар және амалдар",
    question: "Егер 7 · a = 56 болса, a неге тең?",
    options: ["6", "7", "8", "9"],
    correct: 2,
  },
  {
    id: 24,
    grade: 5,
    difficulty: 2,
    topic: "Геометрия",
    question: "Тік төртбұрыштың ұзындығы 12 см, ені 5 см. Ауданы неше см²?",
    options: ["34", "50", "60", "70"],
    correct: 2,
  },
  {
    id: 25,
    grade: 5,
    difficulty: 2,
    topic: "Бөлшектер",
    question: "3/5 – 1/5 айырмасы неге тең?",
    options: ["1/5", "2/5", "2/10", "4/5"],
    correct: 1,
  },
  {
    id: 26,
    grade: 5,
    difficulty: 2,
    topic: "Пайыз",
    question: "100-дің 25%-і неге тең?",
    options: ["20", "25", "30", "50"],
    correct: 1,
  },
  {
    id: 27,
    grade: 5,
    difficulty: 2,
    topic: "Сандар және амалдар",
    question: "420 – 185 айырмасы неге тең?",
    options: ["225", "235", "245", "255"],
    correct: 1,
  },
  // Medium (difficulty 3)
  {
    id: 28,
    grade: 5,
    difficulty: 3,
    topic: "Сандар және амалдар",
    question: "Дүкенде 5 қорап бор сатылды, әр қорапта 24 пакет. 3 пакет ашық қалды. Неше пакет сатылды?",
    options: ["117", "120", "123", "125"],
    correct: 0,
  },
  {
    id: 29,
    grade: 5,
    difficulty: 3,
    topic: "Бөлшектер",
    question: "Мектеп кітапханасында 60 кітаптың 2/5-і оқылды. Оқылмаған кітап нешеу?",
    options: ["24", "32", "36", "40"],
    correct: 2,
  },
  {
    id: 30,
    grade: 5,
    difficulty: 3,
    topic: "Пайыз",
    question: "Көлемі 80 л судың 15%-і жұмсалды. Қалған су неше литр?",
    options: ["65", "66", "68", "70"],
    correct: 2,
  },
  {
    id: 31,
    grade: 5,
    difficulty: 3,
    topic: "Геометрия",
    question: "Үшбұрыштың екі бұрышы 50° және 60°. Үшінші бұрыш неше градус?",
    options: ["60°", "70°", "80°", "90°"],
    correct: 1,
  },
  {
    id: 32,
    grade: 5,
    difficulty: 3,
    topic: "Сандар және амалдар",
    question: "Бір сан екіншісінен 18-ге кіші. Екеуінің қосындысы 64. Үлкен сан қандай?",
    options: ["23", "41", "42", "46"],
    correct: 1,
  },
  {
    id: 33,
    grade: 5,
    difficulty: 3,
    topic: "Бөлшектер",
    question: "1/3 және 1/6 бөлшектерінің ортақ бөлімінің ең кішісі неге тең?",
    options: ["6", "12", "18", "24"],
    correct: 0,
  },
  {
    id: 34,
    grade: 5,
    difficulty: 3,
    topic: "Пайыз",
    question: "Көйлек бағасы 2000 теңгеден 2400 теңгеге өсті. Баға неше пайызға өсті?",
    options: ["18%", "20%", "22%", "25%"],
    correct: 1,
  },
  {
    id: 35,
    grade: 5,
    difficulty: 3,
    topic: "Геометрия",
    question: "Тік төртбұрыштың периметрі 28 см, бір қабырғасы 6 см. Екінші қабырғасы неше см?",
    options: ["6", "7", "8", "9"],
    correct: 2,
  },
  {
    id: 36,
    grade: 5,
    difficulty: 3,
    topic: "Сандар және амалдар",
    question: "4 · (12 + 8) – 15 өрнегінің мәні неге тең?",
    options: ["65", "70", "75", "80"],
    correct: 0,
  },
  {
    id: 37,
    grade: 5,
    difficulty: 3,
    topic: "Бөлшектер",
    question: "2 1/4 + 1 3/4 қосындысы неге тең?",
    options: ["3", "4", "3 1/2", "4 1/2"],
    correct: 1,
  },
  {
    id: 38,
    grade: 5,
    difficulty: 3,
    topic: "Пайыз",
    question: "60 саны 80-нің неше пайызы?",
    options: ["70%", "75%", "80%", "85%"],
    correct: 1,
  },
  {
    id: 39,
    grade: 5,
    difficulty: 3,
    topic: "Геометрия",
    question: "Квадраттың ауданы 81 см². Қабырғасы неше см?",
    options: ["7", "8", "9", "10"],
    correct: 2,
  },
  {
    id: 40,
    grade: 5,
    difficulty: 3,
    topic: "Сандар және амалдар",
    question: "Автобус әр сағатта 65 км жүреді. 4 сағатта неше км жол жүреді?",
    options: ["250", "260", "270", "280"],
    correct: 1,
  },
  {
    id: 41,
    grade: 5,
    difficulty: 3,
    topic: "Бөлшектер",
    question: "5/6 – 1/3 айырмасы неге тең?",
    options: ["1/2", "1/3", "2/3", "4/6"],
    correct: 0,
  },
  {
    id: 42,
    grade: 5,
    difficulty: 3,
    topic: "Пайыз",
    question: "400 теңгенің 30%-і неше теңге?",
    options: ["100", "120", "130", "140"],
    correct: 1,
  },
  // Hard (difficulty 4)
  {
    id: 43,
    grade: 5,
    difficulty: 4,
    topic: "Сандар және амалдар",
    question: "Үш санның орташа мәні 24. Біріншісі 20, екіншісі 28. Үшінші сан қандай?",
    options: ["22", "24", "26", "28"],
    correct: 1,
  },
  {
    id: 44,
    grade: 5,
    difficulty: 4,
    topic: "Бөлшектер",
    question: "Қорапта 72 кәмпит бар. Оның 5/12-і қызыл, қалғанының 1/3-і көк. Көк кәмпит нешеу?",
    options: ["14", "16", "18", "20"],
    correct: 0,
  },
  {
    id: 45,
    grade: 5,
    difficulty: 4,
    topic: "Пайыз",
    question: "Тауар бағасы 20%-ке түсіріліп, кейін 20%-ке өсірілді. Бастапқы баға 500 теңге болса, соңғы баға неше теңге?",
    options: ["480", "490", "500", "520"],
    correct: 0,
  },
  {
    id: 46,
    grade: 5,
    difficulty: 4,
    topic: "Геометрия",
    question: "Тік төртбұрыштың ауданы 48 см², ені 6 см. Периметрі неше см?",
    options: ["26", "28", "30", "32"],
    correct: 1,
  },
  {
    id: 47,
    grade: 5,
    difficulty: 4,
    topic: "Сандар және амалдар",
    question: "Есепте: (144 ÷ 12) · 3 + 28 ÷ 4",
    options: ["39", "40", "41", "43"],
    correct: 2,
  },
  {
    id: 48,
    grade: 5,
    difficulty: 4,
    topic: "Бөлшектер",
    question: "2/5 пен 3/4 бөлшектерін салыстыр. Үлкенінің бөлімі (4) мен кішісінің алымын (2) қосқанда не шығады?",
    options: ["5", "6", "7", "8"],
    correct: 1,
  },
  {
    id: 49,
    grade: 5,
    difficulty: 4,
    topic: "Пайыз",
    question: "Оқушы 40 сұрақтың 85%-ін дұрыс жауаптады. Қате жауап нешеу болды?",
    options: ["4", "5", "6", "7"],
    correct: 2,
  },
  {
    id: 50,
    grade: 5,
    difficulty: 4,
    topic: "Геометрия",
    question: "Тік төртбұрыштың ұзындығы енінен 4 см артық. Периметрі 32 см. Ауданы неше см²?",
    options: ["48", "55", "60", "63"],
    correct: 2,
  },
  {
    id: 51,
    grade: 5,
    difficulty: 4,
    topic: "Сандар және амалдар",
    question: "Әкесінің жасы ұлынан 3 есе үлкен. Екеуінің жастарының қосындысы 52. Ұл неше жаста?",
    options: ["12", "13", "14", "15"],
    correct: 1,
  },
  {
    id: 52,
    grade: 5,
    difficulty: 4,
    topic: "Бөлшектер",
    question: "Бөлшектің алымы 3-ке, бөлімі 4-ке тең. Оған 1/2 қосқанда не шығады?",
    options: ["1 1/4", "1 1/2", "1 3/4", "2"],
    correct: 0,
  },
  // High-pressure (difficulty 5)
  {
    id: 53,
    grade: 5,
    difficulty: 5,
    topic: "Сандар және амалдар",
    question: "Төрт санның орташа мәні 18. Бесінші санды қосқанда орташа 20 болады. Бесінші сан қандай?",
    options: ["26", "28", "30", "32"],
    correct: 1,
  },
  {
    id: 54,
    grade: 5,
    difficulty: 5,
    topic: "Бөлшектер",
    question: "Бір бөлшек 4/5-ке, екіншісі 2/3-ке тең. Қосындысы мен айырмасының айырмасы (яғни қосынды − айырма) неге тең?",
    options: ["2/5", "4/15", "4/3", "8/15"],
    correct: 2,
  },
  {
    id: 55,
    grade: 5,
    difficulty: 5,
    topic: "Пайыз",
    question: "Санды алдымен 25%-ке арттырып, кейін нәтижені 20%-ке азайттық. Бастапқы сан 80 болса, соңғы нәтиже неге тең?",
    options: ["75", "80", "84", "88"],
    correct: 1,
  },
  {
    id: 56,
    grade: 5,
    difficulty: 5,
    topic: "Геометрия",
    question: "Шаршының периметрі мен ауданының қосындысы 32 см. Қабырғасы неше см?",
    options: ["3", "4", "5", "6"],
    correct: 1,
  },
  {
    id: 57,
    grade: 5,
    difficulty: 5,
    topic: "Сандар және амалдар",
    question: "Үш тақ санның қосындысы 51. Олардың ең үлкені қандай?",
    options: ["15", "17", "19", "21"],
    correct: 2,
  },
  // ——— Grade 6 (30): fractions, ratios ———
  { id: 58, grade: 6, difficulty: 1, topic: "Бөлшектер", question: "3/7 + 2/7 қосындысы неге тең?", options: ["5/14", "5/7", "6/7", "1"], correct: 1 },
  { id: 59, grade: 6, difficulty: 1, topic: "Қатынас", question: "Қатынас 2 : 3 болса, 10 : 15 оған тең бе?", options: ["Иә", "Жоқ", "Белгісіз", "Жартылай"], correct: 0 },
  { id: 60, grade: 6, difficulty: 1, topic: "Пайыз", question: "50-нің 20%-і неге тең?", options: ["5", "10", "15", "25"], correct: 1 },
  { id: 61, grade: 6, difficulty: 1, topic: "Бөлшектер", question: "4/5 · 10 көбейтіндісі неге тең?", options: ["6", "8", "9", "10"], correct: 1 },
  { id: 62, grade: 6, difficulty: 2, topic: "Қатынас", question: "Егер a : b = 3 : 4 және b = 8 болса, a неге тең?", options: ["4", "5", "6", "7"], correct: 2 },
  { id: 63, grade: 6, difficulty: 2, topic: "Бөлшектер", question: "7/8 – 3/8 айырмасы неге тең?", options: ["1/2", "4/8", "1/4", "5/8"], correct: 0 },
  { id: 64, grade: 6, difficulty: 2, topic: "Геометрия", question: "Тік төртбұрыштың ауданы 24 см², ені 4 см. Ұзындығы неше см?", options: ["5", "6", "7", "8"], correct: 1 },
  { id: 65, grade: 6, difficulty: 2, topic: "Пайыз", question: "80-нің неше пайызы 20-ға тең?", options: ["20%", "25%", "30%", "40%"], correct: 1 },
  { id: 66, grade: 6, difficulty: 2, topic: "Бөлшектер", question: "1/3 + 1/6 қосындысы неге тең?", options: ["1/2", "2/9", "1/4", "2/6"], correct: 0 },
  { id: 67, grade: 6, difficulty: 3, topic: "Қатынас", question: "Екі санның қатынасы 5 : 7. Кіші сан 25 болса, үлкен сан қандай?", options: ["30", "35", "40", "45"], correct: 1 },
  { id: 68, grade: 6, difficulty: 3, topic: "Бөлшектер", question: "2/3 · 4/5 көбейтіндісі неге тең?", options: ["6/15", "8/15", "6/8", "4/5"], correct: 1 },
  { id: 69, grade: 6, difficulty: 3, topic: "Пайыз", question: "Көлемі 120 л судың 35%-і жұмсалды. Қалған су неше литр?", options: ["72", "78", "80", "85"], correct: 1 },
  { id: 70, grade: 6, difficulty: 3, topic: "Бөлшектер", question: "5/6 ÷ 2/3 бөліндісі неге тең?", options: ["5/4", "5/9", "10/18", "1"], correct: 0 },
  { id: 71, grade: 6, difficulty: 3, topic: "Қатынас", question: "36 алманы 4 : 5 қатынасында бөлсек, үлкен бөлікте неше алма болады?", options: ["16", "18", "20", "22"], correct: 2 },
  { id: 72, grade: 6, difficulty: 3, topic: "Геометрия", question: "Үшбұрыштың бұрыштары 2 : 3 : 4 қатынасында. Ең кіші бұрыш неше градус?", options: ["20°", "40°", "60°", "80°"], correct: 1 },
  { id: 73, grade: 6, difficulty: 3, topic: "Бөлшектер", question: "1 2/5 + 2 1/5 қосындысы неге тең?", options: ["3 3/5", "3 2/5", "3 1/5", "4"], correct: 0 },
  { id: 74, grade: 6, difficulty: 3, topic: "Пайыз", question: "Тауар 400 теңгеден 360 теңгеге түсті. Баға неше пайызға түсті?", options: ["8%", "10%", "12%", "15%"], correct: 1 },
  { id: 75, grade: 6, difficulty: 3, topic: "Бөлшектер", question: "3/4 санының 2/3-і неге тең?", options: ["1/2", "5/12", "6/12", "9/8"], correct: 0 },
  { id: 76, grade: 6, difficulty: 3, topic: "Қатынас", question: "Картада 1 : 50000 масштабта 4 см қашықтық нақтыда неше км?", options: ["1", "2", "2.5", "3"], correct: 1 },
  { id: 77, grade: 6, difficulty: 4, topic: "Бөлшектер", question: "(2/3 + 1/4) – 1/6 өрнегінің мәні неге тең?", options: ["11/12", "1", "13/12", "5/6"], correct: 0 },
  { id: 78, grade: 6, difficulty: 4, topic: "Қатынас", question: "Үш сан 2 : 3 : 5 қатынасында. Орташа сан 36 болса, ең үлкен сан қандай?", options: ["50", "60", "70", "80"], correct: 1 },
  { id: 79, grade: 6, difficulty: 4, topic: "Пайыз", question: "Санды 20%-ке арттырғанда 96 шықты. Бастапқы сан қандай?", options: ["75", "78", "80", "84"], correct: 2 },
  { id: 80, grade: 6, difficulty: 4, topic: "Бөлшектер", question: "Бөлшектің алымы 5-ке, бөлімі 6-ға тең. Оған қандай бөлшекті қосса 1 шығады?", options: ["1/6", "2/6", "1/3", "2/3"], correct: 0 },
  { id: 81, grade: 6, difficulty: 4, topic: "Геометрия", question: "Шаршы мен тік төртбұрыштың периметрлері тең — 24 см. Төртбұрыш ені 3 см. Аудандар айырмасы неше см²?", options: ["27", "30", "33", "36"], correct: 0 },
  { id: 82, grade: 6, difficulty: 4, topic: "Қатынас", question: "Екі қала арасы 240 км. Жылдамдықтар қатынасы 3 : 5. Жаяу жылдамдық 48 км/сағ болса, екінші қанша уақытта жүреді?", options: ["2 сағ", "2.5 сағ", "3 сағ", "4 сағ"], correct: 0 },
  { id: 83, grade: 6, difficulty: 4, topic: "Бөлшектер", question: "1/2 + 1/3 + 1/6 қосындысы неге тең?", options: ["1", "6/11", "5/6", "11/6"], correct: 0 },
  { id: 84, grade: 6, difficulty: 4, topic: "Пайыз", question: "Екі санның 30%-і мен 40%-інің қосындысы 29. Сандардың қосындысы 85 болса, кіші сан қандай?", options: ["35", "40", "45", "50"], correct: 0 },
  { id: 85, grade: 6, difficulty: 4, topic: "Бөлшектер", question: "3/4 – 2/5 айырмасы неге тең?", options: ["7/20", "1/2", "5/9", "11/20"], correct: 0 },
  { id: 86, grade: 6, difficulty: 4, topic: "Қатынас", question: "А классында 24, Б классында 30 оқушы бар. Оларды 3 : 4 : 5 қатынасында үш топқа бөлсек, ең үлкен топта неше адам?", options: ["20", "22", "24", "26"], correct: 2 },
  { id: 87, grade: 6, difficulty: 5, topic: "Бөлшектер", question: "Бөлшектің алымы 2-ге артық, бөлімі 5. Оған 3/10 қосқанда 1 шығады. Бастапқы бөлшек қандай?", options: ["2/5", "3/5", "4/5", "7/10"], correct: 2 },
  // ——— Grade 7 (30): linear equations, algebra ———
  { id: 88, grade: 7, difficulty: 1, topic: "Сызықтық теңдеу", question: "x + 5 = 12 болса, x неге тең?", options: ["5", "6", "7", "8"], correct: 2 },
  { id: 93, grade: 7, difficulty: 1, topic: "Алгебра", question: "2a + 3a қосындысы неге тең?", options: ["5a", "6a", "5a²", "6"], correct: 0 },
  { id: 94, grade: 7, difficulty: 1, topic: "Сызықтық теңдеу", question: "3x = 21 болса, x неге тең?", options: ["5", "6", "7", "8"], correct: 2 },
  { id: 95, grade: 7, difficulty: 1, topic: "Алгебра", question: "5 · (–2) көбейтіндісі неге тең?", options: ["–10", "10", "–7", "7"], correct: 0 },
  { id: 96, grade: 7, difficulty: 2, topic: "Сызықтық теңдеу", question: "2x – 4 = 10 болса, x неге тең?", options: ["5", "6", "7", "8"], correct: 2 },
  { id: 97, grade: 7, difficulty: 2, topic: "Алгебра", question: "–3 + 7 айырмасы неге тең?", options: ["–10", "–4", "4", "10"], correct: 2 },
  { id: 98, grade: 7, difficulty: 2, topic: "Геометрия", question: "Түзудің бір нүктесінен неше түзу өтеді?", options: ["1", "2", "Шексіз көп", "0"], correct: 2 },
  { id: 99, grade: 7, difficulty: 2, topic: "Сызықтық теңдеу", question: "x/4 = 5 болса, x неге тең?", options: ["18", "20", "22", "24"], correct: 1 },
  { id: 100, grade: 7, difficulty: 2, topic: "Алгебра", question: "3(b + 2) жақшаны ашу.", options: ["3b + 2", "3b + 5", "3b + 6", "b + 6"], correct: 2 },
  { id: 101, grade: 7, difficulty: 3, topic: "Сызықтық теңдеу", question: "2(x – 3) = 8 болса, x неге тең?", options: ["5", "6", "7", "8"], correct: 2 },
  { id: 102, grade: 7, difficulty: 3, topic: "Алгебра", question: "Егер a = –1, b = 4 болса, 2a – b неге тең?", options: ["–6", "–4", "4", "6"], correct: 0 },
  { id: 103, grade: 7, difficulty: 3, topic: "Сызықтық теңдеу", question: "5 – 2x = 11 болса, x неге тең?", options: ["–3", "–2", "2", "3"], correct: 0 },
  { id: 104, grade: 7, difficulty: 3, topic: "Алгебра", question: "(–2) · (–3) · (–1) көбейтіндісі неге тең?", options: ["–6", "6", "–5", "5"], correct: 0 },
  { id: 105, grade: 7, difficulty: 3, topic: "Сызықтық теңдеу", question: "3x + 7 = 2x + 12 болса, x неге тең?", options: ["3", "4", "5", "6"], correct: 2 },
  { id: 106, grade: 7, difficulty: 3, topic: "Геометрия", question: "Үшбұрыштың ішкі бұрыштарының қосындысы неше градус?", options: ["90°", "180°", "270°", "360°"], correct: 1 },
  { id: 107, grade: 7, difficulty: 3, topic: "Алгебра", question: "4x – 3x + 2x өрнегін ықшамда.", options: ["3x", "4x", "5x", "9x"], correct: 0 },
  { id: 108, grade: 7, difficulty: 3, topic: "Сызықтық теңдеу", question: "(x + 1)/2 = 4 болса, x неге тең?", options: ["6", "7", "8", "9"], correct: 1 },
  { id: 109, grade: 7, difficulty: 3, topic: "Алгебра", question: "Егер 2m = n болса, 6m – 2n неге тең?", options: ["0", "2n", "4m", "2m"], correct: 0 },
  { id: 110, grade: 7, difficulty: 3, topic: "Сандар", question: "|–7| + |3| неге тең?", options: ["–10", "–4", "4", "10"], correct: 3 },
  { id: 111, grade: 7, difficulty: 4, topic: "Сызықтық теңдеу", question: "2(3x – 1) = 4x + 6 болса, x неге тең?", options: ["2", "3", "4", "5"], correct: 2 },
  { id: 112, grade: 7, difficulty: 4, topic: "Алгебра", question: "Егер x + y = 10 және x – y = 4 болса, x неге тең?", options: ["5", "6", "7", "8"], correct: 2 },
  { id: 113, grade: 7, difficulty: 4, topic: "Сызықтық теңдеу", question: "0.5x + 2 = 5 болса, x неге тең?", options: ["4", "5", "6", "7"], correct: 2 },
  { id: 114, grade: 7, difficulty: 4, topic: "Алгебра", question: "a² + 2a + 1 өрнегінде a = 2 болса, мәні неге тең?", options: ["7", "8", "9", "10"], correct: 2 },
  { id: 115, grade: 7, difficulty: 4, topic: "Геометрия", question: "Тең қабырғалы үшбұрыштың бір бұрышы 60°. Қалған бұрыштары неше градус?", options: ["30° және 90°", "45° және 75°", "60° және 60°", "50° және 70°"], correct: 2 },
  { id: 116, grade: 7, difficulty: 4, topic: "Сызықтық теңдеу", question: "3(x + 2) – 2(x – 1) = 10 болса, x неге тең?", options: ["1", "2", "3", "4"], correct: 1 },
  { id: 117, grade: 7, difficulty: 4, topic: "Алгебра", question: "Екі санның қосындысы 28, айырмасы 6. Үлкен сан қандай?", options: ["15", "16", "17", "18"], correct: 2 },
  { id: 118, grade: 7, difficulty: 4, topic: "Сандар", question: "2³ + 3² неге тең?", options: ["15", "17", "18", "19"], correct: 1 },
  { id: 119, grade: 7, difficulty: 4, topic: "Сызықтық теңдеу", question: "x/3 + x/6 = 4 болса, x неге тең?", options: ["6", "7", "8", "9"], correct: 2 },
  { id: 120, grade: 7, difficulty: 4, topic: "Алгебра", question: "5 – 2(3 – x) = 3x – 4 болса, x неге тең?", options: ["–1", "0", "1", "2"], correct: 0 },
  { id: 121, grade: 7, difficulty: 5, topic: "Сызықтық теңдеу", question: "|2x – 5| = 3 болса, x-тің оң мәні қандай?", options: ["2", "3", "4", "5"], correct: 2 },
  { id: 122, grade: 7, difficulty: 5, topic: "Алгебра", question: "Егер a + 2b = 8 және 2a + b = 10 болса, a + b неге тең?", options: ["4", "5", "6", "7"], correct: 2 },
  { id: 123, grade: 7, difficulty: 5, topic: "Сызықтық теңдеу", question: "(2x – 1)/3 = (x + 2)/2 болса, x неге тең?", options: ["6", "7", "8", "9"], correct: 2 },
  { id: 124, grade: 7, difficulty: 5, topic: "Алгебра", question: "Үш түзудің қиылысу нүктесі нешеу болуы мүмкін?", options: ["0 немесе 1", "0, 1 немесе 3", "Тек 1", "Шексіз көп"], correct: 1 },
  { id: 125, grade: 7, difficulty: 5, topic: "Сандар", question: "2⁴ – 3 · 2² неге тең?", options: ["2", "4", "6", "8"], correct: 1 },
  // ——— Grade 8 (30): algebra, linear equations, geometry ———
  { id: 126, grade: 8, difficulty: 1, topic: "Алгебра", question: "x² · x³ көбейтіндісі неге тең?", options: ["x⁵", "x⁶", "x", "2x⁵"], correct: 0 },
  { id: 127, grade: 8, difficulty: 1, topic: "Сызықтық теңдеу", question: "–2x = 10 болса, x неге тең?", options: ["–5", "5", "–8", "8"], correct: 0 },
  { id: 128, grade: 8, difficulty: 1, topic: "Геометрия", question: "Параллель түзулерді қиятын түзу не деп аталады?", options: ["Секант", "Биссектриса", "Медиана", "Высота"], correct: 0 },
  { id: 129, grade: 8, difficulty: 1, topic: "Алгебра", question: "(–1)¹⁰⁰ неге тең?", options: ["–1", "0", "1", "100"], correct: 2 },
  { id: 130, grade: 8, difficulty: 2, topic: "Алгебра", question: "3x² + 2x² – x² ықшамда.", options: ["4x²", "5x²", "6x²", "4x⁶"], correct: 0 },
  { id: 131, grade: 8, difficulty: 2, topic: "Сызықтық теңдеу", question: "4(x – 2) = 20 болса, x неге тең?", options: ["5", "6", "7", "8"], correct: 2 },
  { id: 132, grade: 8, difficulty: 2, topic: "Геометрия", question: "Тік бұрыш неше градус?", options: ["90°", "180°", "360°", "45°"], correct: 0 },
  { id: 133, grade: 8, difficulty: 2, topic: "Алгебра", question: "√16 + √9 неге тең?", options: ["5", "7", "10", "12"], correct: 1 },
  { id: 134, grade: 8, difficulty: 2, topic: "Функция негіздері", question: "y = 2x түзуі (0;0) нүктесінен өте ме?", options: ["Иә", "Жоқ", "Кейде", "Белгісіз"], correct: 0 },
  { id: 135, grade: 8, difficulty: 3, topic: "Алгебра", question: "x² = 49 болса, x-тің оң мәні қандай?", options: ["5", "6", "7", "8"], correct: 2 },
  { id: 136, grade: 8, difficulty: 3, topic: "Сызықтық теңдеу", question: "2x + 3 = 5x – 9 болса, x неге тең?", options: ["2", "3", "4", "5"], correct: 2 },
  { id: 137, grade: 8, difficulty: 3, topic: "Геометрия", question: "Параллель түзулер арасындағы қашықтық 4 см. Оларды қиюшы түзу екі түзуден 3 см қашықтықта нүкте береді. Қиюшы түзу қалай орналасқан?", options: ["Перпендикуляр", "Көлбеу", "Параллель", "Үстіме-үсті"], correct: 0 },
  { id: 138, grade: 8, difficulty: 3, topic: "Алгебра", question: "(2x)³ ықшамда.", options: ["2x³", "6x³", "8x³", "2³x"], correct: 2 },
  { id: 139, grade: 8, difficulty: 3, topic: "Функция негіздері", question: "y = –3x + 2 түзуінің y осімен қиылысу нүктесінің ординатасы неге тең?", options: ["–3", "0", "2", "3"], correct: 2 },
  { id: 140, grade: 8, difficulty: 3, topic: "Алгебра", question: "Егер x² – 9 = 0 болса, x-тің теріс түбірі қандай?", options: ["–2", "–3", "–4", "–5"], correct: 1 },
  { id: 141, grade: 8, difficulty: 3, topic: "Сызықтық теңдеу", question: "0.2(5x + 10) = 4 болса, x неге тең?", options: ["2", "3", "4", "5"], correct: 1 },
  { id: 142, grade: 8, difficulty: 3, topic: "Геометрия", question: "Үшбұрышта екі бұрыш 40° және 70°. Үшінші бұрыш неше градус?", options: ["60°", "70°", "80°", "90°"], correct: 1 },
  { id: 143, grade: 8, difficulty: 3, topic: "Алгебра", question: "√(25 · 4) неге тең?", options: ["9", "10", "20", "100"], correct: 1 },
  { id: 144, grade: 8, difficulty: 3, topic: "Функция негіздері", question: "y = x – 4 болса, x = 7 кезінде y неге тең?", options: ["2", "3", "4", "5"], correct: 1 },
  { id: 145, grade: 8, difficulty: 3, topic: "Алгебра", question: "x⁵ ÷ x² бөліндісі неге тең?", options: ["x³", "x⁷", "x²", "x¹⁰"], correct: 0 },
  { id: 146, grade: 8, difficulty: 4, topic: "Сызықтық теңдеу", question: "2/(x – 1) = 1 болса (x ≠ 1), x неге тең?", options: ["2", "3", "4", "5"], correct: 1 },
  { id: 147, grade: 8, difficulty: 4, topic: "Алгебра", question: "Егер x + 1/x = 3 болса, x² + 1/x² неге тең?", options: ["5", "6", "7", "9"], correct: 2 },
  { id: 148, grade: 8, difficulty: 4, topic: "Геометрия", question: "Тік төртбұрыштың диагональдары 10 см. Қабырғасы 6 см болса, екінші қабырғасы неше см?", options: ["6", "7", "8", "9"], correct: 2 },
  { id: 149, grade: 8, difficulty: 4, topic: "Алгебра", question: "√50 – √18 ықшамда.", options: ["2√2", "3√2", "4√2", "5√2"], correct: 0 },
  { id: 150, grade: 8, difficulty: 4, topic: "Функция негіздері", question: "y = kx түзуі (2; 6) нүктесінен өтсе, k неге тең?", options: ["2", "3", "4", "5"], correct: 1 },
  { id: 151, grade: 8, difficulty: 4, topic: "Сызықтық теңдеу", question: "|x – 3| = 5 болса, x-тің ең үлкен мәні қандай?", options: ["–2", "5", "8", "10"], correct: 2 },
  { id: 152, grade: 8, difficulty: 4, topic: "Алгебра", question: "(a + b)² – (a – b)² ықшамда.", options: ["2ab", "4ab", "2a²", "2b²"], correct: 1 },
  { id: 153, grade: 8, difficulty: 4, topic: "Геометрия", question: "Ромбының қабырғасы 5 см, бір диагоналі 8 см. Екінші диагоналі неше см?", options: ["4", "5", "6", "7"], correct: 2 },
  { id: 154, grade: 8, difficulty: 4, topic: "Алгебра", question: "x² – 6x + 9 көпмүшесін көбейткішке жікте.", options: ["(x–3)²", "(x+3)²", "(x–2)(x–4)", "x(x–6)"], correct: 0 },
  { id: 155, grade: 8, difficulty: 4, topic: "Сызықтық теңдеу", question: "2x + 3y = 13 және 2x – y = 1 болса, y неге тең?", options: ["2", "3", "4", "5"], correct: 1 },
  { id: 156, grade: 8, difficulty: 5, topic: "Алгебра", question: "Егер √(x + 5) = 4 болса, x неге тең?", options: ["9", "10", "11", "12"], correct: 2 },
  { id: 157, grade: 8, difficulty: 5, topic: "Геометрия", question: "Трапецияның орта сызығы 12 см, табандар қатынасы 1 : 3. Кіші табаны неше см?", options: ["4", "5", "6", "8"], correct: 2 },
  { id: 158, grade: 8, difficulty: 5, topic: "Сызықтық теңдеу", question: "(x + 2)/4 + (x – 1)/3 = 2 болса, x неге тең?", options: ["22/7", "4", "5", "6"], correct: 1 },
  { id: 159, grade: 8, difficulty: 5, topic: "Алгебра", question: "a² + b² = 25 және ab = 12 болса, (a + b)² неге тең?", options: ["47", "48", "49", "50"], correct: 2 },
  { id: 160, grade: 8, difficulty: 5, topic: "Функция негіздері", question: "y = 2x – 4 және y = –x + 5 түзулерінің қиылысу нүктесінің абсциссасы неге тең?", options: ["2", "3", "4", "5"], correct: 1 },
  // ——— Grade 9 (30): quadratic, inequalities ———
  { id: 161, grade: 9, difficulty: 1, topic: "Квадраттық теңдеу", question: "x² = 25 болса, x-тің оң мәні қандай?", options: ["3", "4", "5", "6"], correct: 2 },
  { id: 162, grade: 9, difficulty: 1, topic: "Теңсіздіктер", question: "x + 3 > 5 болса, x қандай сандар жиыны?", options: ["x > 1", "x > 2", "x > 3", "x > 4"], correct: 1 },
  { id: 163, grade: 9, difficulty: 1, topic: "Квадраттық теңдеу", question: "x² – 4 = 0 теңдеуінің түбірлері қандай?", options: ["2 және –2", "4 және –4", "Тек 2", "Тек –2"], correct: 0 },
  { id: 164, grade: 9, difficulty: 1, topic: "Алгебра", question: "(x – 2)(x + 2) ықшамда.", options: ["x² – 4", "x² + 4", "x² – 2", "x² + 2"], correct: 0 },
  { id: 165, grade: 9, difficulty: 2, topic: "Теңсіздіктер", question: "2x ≤ 10 болса, x-тің ең үлкен бүтін мәні қандай?", options: ["4", "5", "6", "7"], correct: 1 },
  { id: 166, grade: 9, difficulty: 2, topic: "Квадраттық теңдеу", question: "x² – 5x + 6 = 0 теңдеуінің түбірлерінің қосындысы неге тең?", options: ["3", "5", "6", "7"], correct: 1 },
  { id: 167, grade: 9, difficulty: 2, topic: "Геометрия", question: "Пифагор теоремасы бойынша тікбұрышты үшбұрышта c² неге тең?", options: ["a + b", "a² + b²", "a – b", "2ab"], correct: 1 },
  { id: 168, grade: 9, difficulty: 2, topic: "Квадраттық теңдеу", question: "x² + 6x + 9 = 0 теңдеуінің дискриминанты неге тең?", options: ["0", "18", "36", "–36"], correct: 0 },
  { id: 169, grade: 9, difficulty: 2, topic: "Теңсіздіктер", question: "–3x < 9 болса, x қалай?", options: ["x > –3", "x < –3", "x > 3", "x < 3"], correct: 0 },
  { id: 170, grade: 9, difficulty: 3, topic: "Квадраттық теңдеу", question: "x² – 7x + 12 = 0 теңдеуінің түбірлерінің көбейтіндісі неге тең?", options: ["7", "12", "–7", "–12"], correct: 1 },
  { id: 171, grade: 9, difficulty: 3, topic: "Теңсіздіктер", question: "x² – 4 > 0 теңсіздігі қай x мәндерінде орындалады?", options: ["x > 2", "x < –2 немесе x > 2", "–2 < x < 2", "x < 2"], correct: 1 },
  { id: 172, grade: 9, difficulty: 3, topic: "Алгебра", question: "x² + 4x + 4 көпмүшесінің көбейткішке жіктелуі қандай?", options: ["(x+2)²", "(x+4)²", "(x–2)²", "x(x+4)"], correct: 0 },
  { id: 173, grade: 9, difficulty: 3, topic: "Квадраттық теңдеу", question: "2x² – 8 = 0 теңдеуінің оң түбірі қандай?", options: ["1", "2", "3", "4"], correct: 1 },
  { id: 174, grade: 9, difficulty: 3, topic: "Геометрия", question: "Үшбұрыштың қабырғалары 6, 8, 10. Ол тікбұрышты үшбұрыш па?", options: ["Иә", "Жоқ", "Белгісіз", "Жартылай"], correct: 0 },
  { id: 175, grade: 9, difficulty: 3, topic: "Теңсіздіктер", question: "3 – 2x ≥ 7 болса, x-тің ең үлкен бүтін мәні қандай?", options: ["–2", "–1", "0", "1"], correct: 0 },
  { id: 176, grade: 9, difficulty: 3, topic: "Квадраттық теңдеу", question: "x² + x – 6 = 0 теңдеуінің теріс түбірі қандай?", options: ["–1", "–2", "–3", "–4"], correct: 2 },
  { id: 177, grade: 9, difficulty: 3, topic: "Алгебра", question: "√(x²) неге тең (x нақты сан)?", options: ["x", "|x|", "–x", "x²"], correct: 1 },
  { id: 178, grade: 9, difficulty: 3, topic: "Теңсіздіктер", question: "|x| < 4 теңсіздігі қандай аралықты береді?", options: ["(–4; 4)", "[–4; 4]", "(–∞; 4)", "(4; ∞)"], correct: 0 },
  { id: 179, grade: 9, difficulty: 3, topic: "Квадраттық теңдеу", question: "x² – 2x – 3 = 0 теңдеуінің түбірлерінің айырмасы неге тең?", options: ["2", "3", "4", "5"], correct: 2 },
  { id: 180, grade: 9, difficulty: 4, topic: "Квадраттық теңдеу", question: "x² + px + 12 = 0 теңдеуінің түбірлері 3 және 4 болса, p неге тең?", options: ["–7", "7", "–12", "12"], correct: 0 },
  { id: 181, grade: 9, difficulty: 4, topic: "Теңсіздіктер", question: "x² – 5x + 6 < 0 теңсіздігінің шешімі қандай аралық?", options: ["(2; 3)", "(–∞; 2)", "(3; ∞)", "Жоқ"], correct: 0 },
  { id: 182, grade: 9, difficulty: 4, topic: "Алгебра", question: "\\( x + \\frac{1}{x} = 4 \\) болса, \\( x^2 + \\frac{1}{x^2} \\) неге тең?", options: ["14", "15", "16", "18"], correct: 0 },
  { id: 183, grade: 9, difficulty: 4, topic: "Квадраттық теңдеу", question: "x² – 6x + k = 0 теңдеуінің бір түбірі 2 болса, k неге тең?", options: ["6", "8", "10", "12"], correct: 1 },
  { id: 184, grade: 9, difficulty: 4, topic: "Геометрия", question: "Тікбұрышты үшбұрышта катеттер 5 және 12. Гипотенуза неше?", options: ["11", "13", "15", "17"], correct: 1 },
  { id: 185, grade: 9, difficulty: 4, topic: "Теңсіздіктер", question: "(x – 1)(x + 2) ≥ 0 теңсіздігінің шешімдер жиыны қандай?", options: ["x ≤ –2 немесе x ≥ 1", "–2 ≤ x ≤ 1", "x ≥ 1", "x ≤ –2"], correct: 0 },
  { id: 186, grade: 9, difficulty: 4, topic: "Квадраттық теңдеу", question: "2x² + 5x – 3 = 0 теңдеуінің түбірлерінің қосындысы неге тең?", options: ["–5/2", "5/2", "–3/2", "3/2"], correct: 0 },
  { id: 187, grade: 9, difficulty: 4, topic: "Алгебра", question: "x² – y² = 24 және x – y = 4 болса, x + y неге тең?", options: ["4", "5", "6", "7"], correct: 2 },
  { id: 188, grade: 9, difficulty: 4, topic: "Квадраттық теңдеу", question: "x² + 4x + c = 0 теңдеуінің бір түбірі болуы үшін c неге тең болуы керек?", options: ["2", "3", "4", "5"], correct: 2 },
  { id: 189, grade: 9, difficulty: 4, topic: "Теңсіздіктер", question: "1/x > 1/3 теңсіздігі (x > 0) қай аралықта орындалады?", options: ["(0; 3)", "(3; ∞)", "(–∞; 3)", "Жоқ"], correct: 0 },
  { id: 190, grade: 9, difficulty: 5, topic: "Квадраттық теңдеу", question: "x² – (k+1)x + k = 0 теңдеуінің түбірлерінің қосындысы 5 болса, k неге тең?", options: ["3", "4", "5", "6"], correct: 1 },
  { id: 191, grade: 9, difficulty: 5, topic: "Теңсіздіктер", question: "|x – 2| + |x + 2| < 6 теңсіздігінің бүтін шешімдері нешеу?", options: ["3", "5", "7", "9"], correct: 1 },
  { id: 192, grade: 9, difficulty: 5, topic: "Алгебра", question: "x² + 1/x² = 7 болса, x + 1/x-тің оң мәні неге тең?", options: ["2", "3", "4", "5"], correct: 1 },
  { id: 193, grade: 9, difficulty: 5, topic: "Квадраттық теңдеу", question: "x² + 2ax + a² – 1 = 0 теңдеуінің түбірлері нақты болуы үшін a қандай болуы керек?", options: ["Кез келген a", "a ≥ 1", "a ≤ –1", "–1 ≤ a ≤ 1"], correct: 0 },
  { id: 194, grade: 9, difficulty: 5, topic: "Геометрия", question: "Үшбұрыш қабырғалары 7, 24, 25. Оның ауданы нешеге тең?", options: ["84", "90", "96", "100"], correct: 0 },
  // ——— Grade 10 (30): functions, probability, trig basics ———
  { id: 195, grade: 10, difficulty: 1, topic: "Функциялар", question: "y = x² функциясының анықталу облысы қандай?", options: ["Тек оң сандар", "Тек теріс сандар", "Барлық нақты сандар", "Тек бүтін сандар"], correct: 2 },
  {
    id: 196,
    grade: 10,
    difficulty: 1,
    topic: "Тригонометрия негіздері",
    question: "\\[ \\sin^2\\alpha + \\cos^2\\alpha \\] неге тең?",
    options: ["0", "1", "2", "\\( \\sin 2\\alpha \\)"],
    correct: 1,
  },
  {
    id: 197,
    grade: 10,
    difficulty: 1,
    topic: "Ықтималдық",
    question: "\\[ P(A) = ? \\quad \\text{A: «елтаңба түсуі» (тиын бір рет лақтырылады)} \\]",
    options: ["\\( 0 \\)", "\\( \\frac{1}{4} \\)", "\\( \\frac{1}{2} \\)", "\\( 1 \\)"],
    correct: 2,
  },
  { id: 198, grade: 10, difficulty: 1, topic: "Функциялар", question: "f(x) = 2x + 1 болса, f(3) неге тең?", options: ["5", "6", "7", "8"], correct: 2 },
  {
    id: 199,
    grade: 10,
    difficulty: 2,
    topic: "Тригонометрия негіздері",
    question: "\\[ \\sin 30^{\\circ} \\] неге тең?",
    options: ["0.5", "√2/2", "√3/2", "1"],
    correct: 0,
  },
  {
    id: 200,
    grade: 10,
    difficulty: 2,
    topic: "Ықтималдық",
    question: "\\[ P(A) = ? \\quad \\text{A: «1-ден 10-ға дейін жұп сан шығу»} \\]",
    options: ["\\( \\frac{3}{10} \\)", "\\( \\frac{2}{5} \\)", "\\( \\frac{1}{2} \\)", "\\( \\frac{3}{5} \\)"],
    correct: 2,
  },
  { id: 201, grade: 10, difficulty: 2, topic: "Функциялар", question: "y = √x функциясы қай аралықта анықталған?", options: ["x ≥ 0", "x > 0", "Барлық нақты", "x ≤ 0"], correct: 0 },
  {
    id: 202,
    grade: 10,
    difficulty: 2,
    topic: "Геометрия",
    question: "Дөңгелектің радиусы 5. Доғаның ұзындығы \\( \\pi \\) болса, орталық бұрыш неше радиан?",
    options: [
      "\\( \\frac{\\pi}{5} \\)",
      "\\( \\frac{\\pi}{4} \\)",
      "\\( \\frac{\\pi}{3} \\)",
      "\\( \\frac{\\pi}{2} \\)",
    ],
    correct: 0,
  },
  {
    id: 203,
    grade: 10,
    difficulty: 2,
    topic: "Тригонометрия негіздері",
    question: "\\[ \\cos 60^{\\circ} \\] неге тең?",
    options: ["0.5", "√3/2", "√2/2", "1"],
    correct: 0,
  },
  { id: 204, grade: 10, difficulty: 3, topic: "Функциялар", question: "f(x) = x² – 4 болса, f(x) = 0 теңдеуінің түбірлері қандай?", options: ["2 және –2", "0 және 4", "Тек 2", "Тек –2"], correct: 0 },
  {
    id: 205,
    grade: 10,
    difficulty: 3,
    topic: "Ықтималдық",
    question: "\\[ P(A) = ? \\quad \\text{A: «екі сүйекте қосындысы } 7 \\text{ болу»} \\]",
    options: ["\\( \\frac{1}{12} \\)", "\\( \\frac{1}{6} \\)", "\\( \\frac{1}{4} \\)", "\\( \\frac{1}{3} \\)"],
    correct: 1,
  },
  {
    id: 206,
    grade: 10,
    difficulty: 3,
    topic: "Тригонометрия негіздері",
    question: "\\[ \\tan 45^{\\circ} \\] неге тең?",
    options: ["0", "0.5", "1", "√3"],
    correct: 2,
  },
  { id: 207, grade: 10, difficulty: 3, topic: "Функциялар", question: "y = |x| функциясы x = 0 нүктесінде дифференциалданады ма?", options: ["Иә", "Жоқ", "Шартты", "Белгісіз"], correct: 1 },
  { id: 208, grade: 10, difficulty: 3, topic: "Алгебра", question: "log₂8 неге тең?", options: ["2", "3", "4", "5"], correct: 1 },
  {
    id: 209,
    grade: 10,
    difficulty: 3,
    topic: "Тригонометрия негіздері",
    question: "\\[ \\sin\\left(90^{\\circ} - \\alpha\\right) \\] неге тең?",
    options: [
      "\\( \\sin \\alpha \\)",
      "\\( \\cos \\alpha \\)",
      "\\( \\tan \\alpha \\)",
      "\\( -\\cos \\alpha \\)",
    ],
    correct: 1,
  },
  {
    id: 210,
    grade: 10,
    difficulty: 3,
    topic: "Ықтималдық",
    question: "\\[ P(A) = ? \\quad \\text{A: «қораптан қызыл шар алу»} \\]",
    options: ["\\( \\frac{3}{8} \\)", "\\( \\frac{5}{8} \\)", "\\( \\frac{1}{2} \\)", "\\( \\frac{5}{3} \\)"],
    correct: 1,
  },
  { id: 211, grade: 10, difficulty: 3, topic: "Функциялар", question: "y = 2ˣ функциясының мәндер жиыны қандай?", options: ["(0; ∞)", "[0; ∞)", "Барлық нақты", "Тек оң бүтін"], correct: 0 },
  { id: 212, grade: 10, difficulty: 3, topic: "Геометрия", question: "Радиусы R дөңгелектің ауданы неге тең?", options: ["2πR", "πR²", "πR", "R²"], correct: 1 },
  {
    id: 213,
    grade: 10,
    difficulty: 3,
    topic: "Тригонометрия негіздері",
    question: "\\[ \\sin 2\\alpha \\] неге тең?",
    options: [
      "\\( 2 \\sin \\alpha \\)",
      "\\( 2 \\sin \\alpha \\cos \\alpha \\)",
      "\\( \\sin \\alpha + \\cos \\alpha \\)",
      "\\( \\sin^2 \\alpha \\)",
    ],
    correct: 1,
  },
  { id: 214, grade: 10, difficulty: 3, topic: "Алгебра", question: "2³ · 2⁴ неге тең?", options: ["2⁷", "2¹²", "4⁷", "8⁴"], correct: 0 },
  { id: 215, grade: 10, difficulty: 4, topic: "Функциялар", question: "f(x) = x³ – 3x болса, f(–1) неге тең?", options: ["–2", "0", "2", "4"], correct: 2 },
  {
    id: 216,
    grade: 10,
    difficulty: 4,
    topic: "Ықтималдық",
    question: "\\[ P(A) = ? \\quad \\text{A: «3 лақтыруда дәл 2 елтаңба»} \\]",
    options: ["\\( \\frac{1}{8} \\)", "\\( \\frac{2}{8} \\)", "\\( \\frac{3}{8} \\)", "\\( \\frac{4}{8} \\)"],
    correct: 2,
  },
  {
    id: 217,
    grade: 10,
    difficulty: 4,
    topic: "Тригонометрия негіздері",
    question: "\\[ \\cos 2\\alpha \\] неге тең?",
    options: [
      "\\( 2 \\cos \\alpha \\)",
      "\\( \\cos^2 \\alpha - \\sin^2 \\alpha \\)",
      "\\( 2 \\cos^2 \\alpha \\)",
      "\\( 1 - \\sin \\alpha \\)",
    ],
    correct: 1,
  },
  { id: 218, grade: 10, difficulty: 4, topic: "Функциялар", question: "y = 1/x функциясының графигі қандай фигура?", options: ["Түзу", "Парабола", "Гипербола", "Шеңбер"], correct: 2 },
  { id: 219, grade: 10, difficulty: 4, topic: "Алгебра", question: "log₃(x – 1) = 2 болса, x неге тең?", options: ["8", "9", "10", "11"], correct: 2 },
  {
    id: 220,
    grade: 10,
    difficulty: 4,
    topic: "Тригонометрия негіздері",
    question:
      "\\( \\sin \\alpha = \\frac{3}{5} \\) болса (\\( \\alpha \\) сүйір), \\( \\cos \\alpha \\) неге тең?",
    options: ["\\( \\frac{3}{5} \\)", "\\( \\frac{4}{5} \\)", "\\( \\frac{5}{3} \\)", "\\( \\frac{1}{5} \\)"],
    correct: 1,
  },
  {
    id: 221,
    grade: 10,
    difficulty: 4,
    topic: "Ықтималдық",
    question: "\\[ P(A) = ? \\quad \\text{A: «52 картаның ішінен туз шығу»} \\]",
    options: ["\\( \\frac{1}{13} \\)", "\\( \\frac{1}{52} \\)", "\\( \\frac{4}{52} \\)", "\\( \\frac{1}{4} \\)"],
    correct: 0,
  },
  { id: 222, grade: 10, difficulty: 4, topic: "Функциялар", question: "f(x) = x² + 2x + 1 болса, f(x)-тің ең кіші мәні неге тең?", options: ["–1", "0", "1", "2"], correct: 1 },
  { id: 223, grade: 10, difficulty: 4, topic: "Геометрия", question: "Цилиндр биіктігі 4, табан радиусы 3. Бүйір бетінің ауданы неге тең?", options: ["12π", "24π", "36π", "48π"], correct: 1 },
  { id: 224, grade: 10, difficulty: 4, topic: "Алгебра", question: "log 100 + log 10 неге тең (ондық логарифм)?", options: ["2", "3", "11", "110"], correct: 1 },
  { id: 225, grade: 10, difficulty: 5, topic: "Функциялар", question: "f(x) = x² және g(x) = x + 2 болса, f(g(1)) неге тең?", options: ["5", "7", "9", "11"], correct: 2 },
  {
    id: 226,
    grade: 10,
    difficulty: 5,
    topic: "Ықтималдық",
    question: "\\[ P(A) = ? \\quad \\text{A: «9 оқушының ішінен 2 қыз таңдау»} \\]",
    options: ["\\( \\frac{5}{18} \\)", "\\( \\frac{10}{36} \\)", "\\( \\frac{5}{9} \\)", "\\( \\frac{1}{2} \\)"],
    correct: 0,
  },
  {
    id: 227,
    grade: 10,
    difficulty: 5,
    topic: "Тригонометрия негіздері",
    question:
      "\\( \\sin \\alpha + \\cos \\alpha = 1 \\) болса (\\( 0 \\le \\alpha \\le \\frac{\\pi}{2} \\)), \\( \\sin 2\\alpha \\) неге тең?",
    options: ["0", "0.5", "1", "2"],
    correct: 0,
  },
  { id: 228, grade: 10, difficulty: 5, topic: "Алгебра", question: "2^(log₂ 7) неге тең?", options: ["2", "7", "14", "49"], correct: 1 },
  { id: 229, grade: 10, difficulty: 5, topic: "Функциялар", question: "y = x² – 4x + 3 параболасының төбесінің абсциссасы неге тең?", options: ["1", "2", "3", "4"], correct: 1 },
  // ——— Grade 11 (30) ———
  { id: 230, grade: 11, difficulty: 1, topic: "Функциялар", question: "y = x³ функциясы тақ функция ма?", options: ["Иә", "Жоқ", "Жұп", "Периодты"], correct: 0 },
  {
    id: 231,
    grade: 11,
    difficulty: 1,
    topic: "Ықтималдық",
    question: "\\[ 0 \\le P(A) \\le 1 \\quad \\text{қай аралық дұрыс?} \\]",
    options: ["[0; 1]", "(0; 1)", "[−1; 1]", "(0; ∞)"],
    correct: 0,
  },
  { id: 232, grade: 11, difficulty: 1, topic: "Жоғары алгебра", question: "C(n, 0) неге тең (комбинаторика)?", options: ["0", "1", "n", "n!"], correct: 1 },
  {
    id: 233,
    grade: 11,
    difficulty: 1,
    topic: "Тригонометрия",
    question: "\\[ \\cos(-\\alpha) \\] неге тең?",
    options: [
      "\\( -\\cos \\alpha \\)",
      "\\( \\cos \\alpha \\)",
      "\\( \\sin \\alpha \\)",
      "\\( -\\sin \\alpha \\)",
    ],
    correct: 1,
  },
  { id: 234, grade: 11, difficulty: 2, topic: "Функциялар", question: "f(x) = 1/x болса, f(x) + f(–x) неге тең?", options: ["0", "1", "2/x", "2"], correct: 0 },
  {
    id: 235,
    grade: 11,
    difficulty: 2,
    topic: "Ықтималдық",
    question: "\\[ A(5,2) = ? \\quad \\text{(орналастыру саны)} \\]",
    options: ["10", "20", "25", "120"],
    correct: 1,
  },
  { id: 236, grade: 11, difficulty: 2, topic: "Жоғары алгебра", question: "n! / (n–1)! ықшамда.", options: ["1", "n", "n–1", "n+1"], correct: 1 },
  {
    id: 237,
    grade: 11,
    difficulty: 2,
    topic: "Тригонометрия",
    question: "\\[ \\sin\\left(\\frac{\\pi}{2} - \\alpha\\right) \\] неге тең?",
    options: [
      "\\( \\sin \\alpha \\)",
      "\\( \\cos \\alpha \\)",
      "\\( -\\cos \\alpha \\)",
      "\\( \\tan \\alpha \\)",
    ],
    correct: 1,
  },
  { id: 238, grade: 11, difficulty: 2, topic: "Геометрия", question: "Конустың көлемі V = (1/3)πr²h. r = 3, h = 4 болса, V неге тең?", options: ["12π", "18π", "24π", "36π"], correct: 0 },
  { id: 239, grade: 11, difficulty: 3, topic: "Функциялар", question: "y = ln x функциясы қай нүктеде 1-ге тең?", options: ["x = 0", "x = 1", "x = e", "x = 10"], correct: 2 },
  {
    id: 240,
    grade: 11,
    difficulty: 3,
    topic: "Ықтималдық",
    question:
      "\\[ P(A) \\approx ? \\quad \\text{A: «6 сүйек лақтырғанда дәл бір } 6 \\text{ түсуі»} \\]",
    options: [
      "\\( \\frac{1}{6} \\)",
      "\\( \\frac{5}{6} \\)",
      "\\( (\\tfrac{5}{6})^5 \\cdot \\tfrac{1}{6} \\)",
      "\\( \\frac{1}{36} \\)",
    ],
    correct: 2,
  },
  { id: 241, grade: 11, difficulty: 3, topic: "Жоғары алгебра", question: "C(5, 2) неге тең?", options: ["5", "10", "20", "25"], correct: 1 },
  {
    id: 242,
    grade: 11,
    difficulty: 3,
    topic: "Тригонометрия",
    question:
      "\\( \\sin \\alpha = \\frac{1}{2} \\) болса, \\( 0^{\\circ} \\le \\alpha \\le 180^{\\circ} \\) аралығында \\( \\alpha \\) неше градус болуы мүмкін?",
    options: ["Тек 30°", "30° немесе 150°", "Тек 150°", "60°"],
    correct: 1,
  },
  { id: 243, grade: 11, difficulty: 3, topic: "Функциялар", question: "y = eˣ функциясының туындысы неге тең?", options: ["eˣ", "xeˣ⁻¹", "e", "0"], correct: 0 },
  { id: 244, grade: 11, difficulty: 3, topic: "Геометрия", question: "Сфераның ауданы 4πR². Радиусы 2 болса, ауданы неге тең?", options: ["8π", "16π", "32π", "64π"], correct: 1 },
  {
    id: 245,
    grade: 11,
    difficulty: 3,
    topic: "Ықтималдық",
    question: "\\[ P(A)=0.4,\\ P(B)=0.5,\\ A \\perp B. \\quad P(A \\cap B) = ? \\]",
    options: ["0.1", "0.2", "0.9", "1"],
    correct: 1,
  },
  { id: 246, grade: 11, difficulty: 3, topic: "Жоғары алгебра", question: "(1 + i)² неге тең (i — жорамал бірлік)?", options: ["0", "2i", "1 + 2i", "2 + 2i"], correct: 1 },
  {
    id: 247,
    grade: 11,
    difficulty: 3,
    topic: "Тригонометрия",
    question:
      "\\[ \\sin \\alpha + \\sin \\beta = 2 \\sin\\left(\\frac{\\alpha+\\beta}{2}\\right) \\cos\\left(\\frac{\\alpha-\\beta}{2}\\right) \\] \\( \\sin 50^{\\circ} + \\sin 10^{\\circ} \\) неге тең?",
    options: [
      "\\( \\sin 60^{\\circ} \\)",
      "\\( 2 \\sin 30^{\\circ} \\cos 20^{\\circ} \\)",
      "\\( \\cos 20^{\\circ} \\)",
      "\\( 2 \\cos 30^{\\circ} \\)",
    ],
    correct: 1,
  },
  { id: 248, grade: 11, difficulty: 3, topic: "Функциялар", question: "f(x) = x² туындысы нөлге тең болатын нүкте қандай?", options: ["x = –1", "x = 0", "x = 1", "Жоқ"], correct: 1 },
  { id: 249, grade: 11, difficulty: 4, topic: "Функциялар", question: "∫₀¹ x dx интегралы неге тең?", options: ["0", "0.5", "1", "2"], correct: 1 },
  {
    id: 250,
    grade: 11,
    difficulty: 4,
    topic: "Ықтималдық",
    question:
      "\\[ P(A) = 0.8 \\quad \\text{(бір тестте дұрыс жауап).} \\quad P(A_1 A_2 A_3) = ? \\]",
    options: ["0.24", "0.512", "0.8", "2.4"],
    correct: 1,
  },
  { id: 251, grade: 11, difficulty: 4, topic: "Жоғары алгебра", question: "x³ – 1 = 0 теңдеуінің нақты түбірлері нешеу?", options: ["0", "1", "2", "3"], correct: 1 },
  {
    id: 252,
    grade: 11,
    difficulty: 4,
    topic: "Тригонометрия",
    question:
      "\\[ \\sin 75^{\\circ} = \\sin\\left(45^{\\circ} + 30^{\\circ}\\right) = \\sin 45^{\\circ} \\cos 30^{\\circ} + \\cos 45^{\\circ} \\sin 30^{\\circ} \\] Осы жазудағы \\( \\sin 45^{\\circ} \\) және \\( \\cos 30^{\\circ} \\) коэффициенттері қандай?",
    options: ["√2/2 және √3/2", "1/2 және √3/2", "√6/4", "sin 45 cos 30 + cos 45 sin 30"],
    correct: 3,
  },
  { id: 253, grade: 11, difficulty: 4, topic: "Функциялар", question: "y = x · eˣ болса, y'(0) неге тең?", options: ["0", "1", "e", "2"], correct: 1 },
  { id: 254, grade: 11, difficulty: 4, topic: "Геометрия", question: "Шар көлемі V = (4/3)πR³. R = 3 болса, V неге тең?", options: ["12π", "27π", "36π", "48π"], correct: 2 },
  {
    id: 255,
    grade: 11,
    difficulty: 4,
    topic: "Ықтималдық",
    question:
      "\\[ P(A) = ? \\quad \\text{A: «1–20 билеттерінен 3 қатар нөмір таңдау»} \\]",
    options: [
      "\\( \\frac{1}{20} \\)",
      "\\( \\frac{3}{20} \\)",
      "\\( \\frac{1}{1140} \\)",
      "\\( \\frac{3}{1140} \\)",
    ],
    correct: 2,
  },
  { id: 256, grade: 11, difficulty: 4, topic: "Жоғары алгебра", question: "Матрицаның анықтауышы det(A)=2, det(B)=3. det(AB) неге тең?", options: ["5", "6", "2/3", "3/2"], correct: 1 },
  {
    id: 257,
    grade: 11,
    difficulty: 4,
    topic: "Тригонометрия",
    question: "\\[ 2 \\cos^2 x - 1 \\] неге тең?",
    options: ["\\( \\cos 2x \\)", "\\( \\sin 2x \\)", "\\( \\cos^2 x \\)", "\\( 2 \\cos x \\)"],
    correct: 0,
  },
  { id: 258, grade: 11, difficulty: 4, topic: "Функциялар", question: "f(x) = x³ – 3x болса, f-тің өсу аралығы қандай?", options: ["(–∞; –1) ∪ (1; ∞)", "(–1; 1)", "Тек (0; ∞)", "Барлық нақты"], correct: 0 },
  { id: 259, grade: 11, difficulty: 5, topic: "Функциялар", question: "lim(x→0) (sin x)/x шегі неге тең?", options: ["0", "0.5", "1", "Шексіздік"], correct: 2 },
  {
    id: 260,
    grade: 11,
    difficulty: 5,
    topic: "Ықтималдық",
    question:
      "\\[ P(A) = ? \\quad \\text{A: «ойын сүйегін 4 рет лақтырғанда дәл 2 рет } 6 \\text{ түсуі»} \\]",
    options: [
      "\\( C(4,2)\\left(\\tfrac{1}{6}\\right)^2\\left(\\tfrac{5}{6}\\right)^2 \\)",
      "\\( \\tfrac{1}{6} \\)",
      "\\( \\tfrac{2}{6} \\)",
      "\\( \\tfrac{4}{36} \\)",
    ],
    correct: 0,
  },
  { id: 261, grade: 11, difficulty: 5, topic: "Жоғары алгебра", question: "z = 1 + i болса, |z| неге тең?", options: ["1", "√2", "2", "2i"], correct: 1 },
  {
    id: 262,
    grade: 11,
    difficulty: 5,
    topic: "Тригонометрия",
    question: "\\[ \\sin 3\\alpha \\] неге тең?",
    options: [
      "\\( 3 \\sin \\alpha \\)",
      "\\( 3 \\sin \\alpha - 4 \\sin^3 \\alpha \\)",
      "\\( \\sin \\alpha \\cos 2\\alpha \\)",
      "\\( 2 \\sin \\alpha \\cos \\alpha \\)",
    ],
    correct: 1,
  },
  { id: 263, grade: 11, difficulty: 5, topic: "Функциялар", question: "∫ eˣ dx неге тең?", options: ["eˣ + C", "xeˣ + C", "eˣ/x + C", "eˣ²/2 + C"], correct: 0 },
]
